In [1]:
import numpy as np
from random import randint
import sys

In [2]:
X=np.array([[1,1,1],[1,-1,1],[-1,1,1],[-1,-1,1]])
X

array([[ 1,  1,  1],
       [ 1, -1,  1],
       [-1,  1,  1],
       [-1, -1,  1]])

In [3]:
Y_ad=np.array([[1],[-1],[-1],[-1]])
Y_ad

array([[ 1],
       [-1],
       [-1],
       [-1]])

In [4]:
weights_ad=np.zeros((3))
weights_ad

array([0., 0., 0.])

In [5]:
def update_weight_ad(X, Y, weights):
    for i in range(4):
        weights = weights+X[i]*Y[i]
        # print weights
        slope = -(weights[0]/weights[1])
        c = -(weights[2]/weights[0])
        if slope < 0 and weights[0] > 0:
            weights_main = weights
        return weights_main


In [6]:
weights_ad = update_weight_ad(X,Y_ad,weights_ad)

In [7]:
def check_learning(X,weights,rand_int):
    Yin=0
    for i in range(3):
        Yin+=X[rand_int,i]*weights[i]
    if Yin<0:
        Yin=-1
    else:
        Yin=1    
    return Yin

In [8]:
Yin=check_learning(X,weights_ad,2)
Yin

1